### ISSUE TITLE
Import of `composable_diffusion.losses` sub-module that does not exist anymore

### ISSUE THREAD

**Issue by dashstander** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#1]
This is the line of code:
https://github.com/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch/blob/2b704950c4348cc70b2a441ca6d546d5a5173774/composable_diffusion/gaussian_diffusion.py#L12
Did something happen to this file? I can't get the script to run because of this error.
More broadly, what's the difference between the provided script (which imports from the `composable_diffusion` module) and the Colab (which only imports from the `glide_text2im` module)?

**Comment by nanlliu** [comment]
should be good for now. Just pull the latest update. If there is still an issue, feel free to reopen this ticket.
