### ISSUE TITLE
minor fix in inference command

### ISSUE THREAD

**Issue by tejas-gokhale** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#10]
https://github.com/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#python

The prompt should be put in quotes.
`python scripts/image_sample_compose_glide.py --prompt "a camel | a forest"`

Also the commands for GLIDE and Stable-Diffusion should be swapped.

Thanks! Great work!

**Comment by nanlliu** [comment]
thanks for pointing that out! just fixed.

**Comment by tejas-gokhale** [comment]
another point:

in https://github.com/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch/blob/d047d034da5ab42e54137f2ce2c05fd78e2b220f/scripts/image_sample_compose_stable_diffusion.py#L14

add default variable types (Otherwise it throws errors)
```
parser.add_argument("--steps", default=50, type=int)
parser.add_argument("--scale", default=10, type=float)
```

You can close the issue after updating it!  Thanks!

**Comment by nanlliu** [comment]
thanks! fixed.
