### ISSUE TITLE
Stable Diffusion uses standard pipeline, where is composition?

### ISSUE THREAD

**Issue by ghost** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#11]
https://huggingface.co/spaces/Shuang59/Composable-Diffusion/blob/main/app.py

With Stable Diffusion there appears to be no composition happening?
The code just uses the standard pipeline from diffusers.

```
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    use_auth_token=st.secrets["USER_TOKEN"]
).to(device)

```

Also, what happened to the NOT operator in the paper? It appears absent.

**Comment by nanlliu** [comment]
here we pip install our modified diffusers package for compositionality.
(see https://github.com/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch/blob/main/requirements.txt)

see modification details at https://github.com/nanlliu/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L143-L146.

We split the string at https://github.com/nanlliu/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L74

hope that helps.

For NOT operator, you need to negate the score on which you condition.
For simplicity, we just have AND operator for now.

**Comment by ghost** [comment]
I see now, it would have been better to just create your own pipeline using the original diffusers.
