### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by ChanghaoShih** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#13]
Hi, it's a very interesting paper and I enjoyed it. I am wondering if you could release the pretrained diffusion models and classifiers on FFHQ dataset (models used to generate table3 in A2)? Thank you very much.

**Comment by nanlliu** [comment]
We don't plan to release the FFHQ pretrained model due to privacy issues related to deepfake human face.
It should be quite easy to reproduce the FFHQ results.
