### ISSUE TITLE
Are the composed models separately trained?

### ISSUE THREAD

**Issue by ziqihuangg** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#15]
Hi, thanks for open sourcing this exciting work.

I wonder whether the composed diffusion models are separately trained?
For example, for composing facial attributes, is there one model for synthesising faces with Smiling, and another separately trained model for synthesising faces with Glasses? Or we only need to train on FFHQ once to obtain P(x|c), where "c" can be Smiling or Glasses or Male?

Thank you very much!

**Comment by nanlliu** [comment]
In this paper, we used the same model trained on all possible attributes for a specific dataset for composing attributes.
But it should also work if you train separate models on each attribute individually.

hope that helps!

**Comment by ziqihuangg** [comment]
Got it. Thank you very much!
