### ISSUE TITLE
data is not defined

### ISSUE THREAD

**Issue by realliyifei** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#18]
https://github.com/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch/blob/ff3b5979810d71ef7496243ed1ee2ec32f5ce294/composable_diffusion/image_datasets.py#L195

here, `data.Dataset` should be `Dataset`

**Comment by nanlliu** [comment]
fixed.
