### ISSUE TITLE
I did something stupid and got a error!

### ISSUE THREAD

**Issue by Vizzarto** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#23]
I tried to install Composable-Diffusion via the Install URL using this link (https://github.com/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch.git) , and now I don't have Stable Diffusion running, it gives this error: 
Launching Web UI with arguments: --xformers --autolaunch
usage: launch.py [-h] [--image_size IMAGE_SIZE] [--num_channels NUM_CHANNELS] [--num_res_blocks NUM_RES_BLOCKS]
                 [--channel_mult CHANNEL_MULT] [--num_heads NUM_HEADS] [--num_head_channels NUM_HEAD_CHANNELS]
                 [--num_heads_upsample NUM_HEADS_UPSAMPLE] [--attention_resolutions ATTENTION_RESOLUTIONS]
                 [--dropout DROPOUT] [--text_ctx TEXT_CTX] [--xf_width XF_WIDTH] [--xf_layers XF_LAYERS]
                 [--xf_heads XF_HEADS] [--xf_final_ln XF_FINAL_LN] [--xf_padding XF_PADDING]
                 [--diffusion_steps DIFFUSION_STEPS] [--noise_schedule NOISE_SCHEDULE]
                 [--timestep_respacing TIMESTEP_RESPACING] [--use_scale_shift_norm USE_SCALE_SHIFT_NORM]
                 [--resblock_updown RESBLOCK_UPDOWN] [--use_fp16 USE_FP16] [--cache_text_emb CACHE_TEXT_EMB]
                 [--inpaint INPAINT] [--super_res SUPER_RES] [--raw_unet RAW_UNET] [--learn_sigma LEARN_SIGMA]
                 [--use_kl USE_KL] [--rescale_timesteps RESCALE_TIMESTEPS]
                 [--rescale_learned_sigmas RESCALE_LEARNED_SIGMAS] [--num_classes NUM_CLASSES] [--dataset DATASET]
                 --ckpt_path CKPT_PATH [--weights WEIGHTS [WEIGHTS ...]]
launch.py: error: the following arguments are required: --ckpt_path

Please tell me how can i fix it? Can i delete some files or jump on previous stable version some how?

**Comment by Vizzarto** [comment]
I solved the problem)

**Comment by nikoharo** [comment]
hello, sorry to bother you, can I ask how you solved it?

**Comment by Vizzarto** [comment]
@nikoharo  Hi, I just deleted the corresponding folder from the extensions folder.
