### ISSUE TITLE
Binary classifier for computing evaluation metrics of CLEVR?

### ISSUE THREAD

**Issue by kyonofx** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#24]
Thank you for the great paper and codebase!

Will it be possible also to open-source the binary classifier used for the evaluation of CLEVR tasks? Even better if the trained models can be released, too.

Thanks again in advance.

**Comment by nanlliu** [comment]
thanks for asking. i will release the code for the classifier and the trained one within next couple of days once i get the time to do it.

**Comment by kyonofx** [comment]
Thank you for the prompt reply! Looking forward to it.

**Comment by nanlliu** [comment]
Sorry about the wait. Please see `classifier` folder and let me know if there are any other issues.

**Comment by kyonofx** [comment]
Thank you very much. This is very helpful!
