### ISSUE TITLE
Question about the Equation 3.3

### ISSUE THREAD

**Issue by dongzhuoyao** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#6]
Hi, thanks for the great work.

I am a beginner of this topic, could you elaborate why your formulation of Eq 3.3 is different from DDPM paper?

your paper:
![image](https://user-images.githubusercontent.com/13537104/181720923-cf41748e-f531-44f3-9dd4-3e52a6b22c46.png)

DDPM paper:
![image](https://user-images.githubusercontent.com/13537104/181720975-39d1f866-486b-42b3-9439-c3366f8731bb.png)

Some coefficients are missing, but to my understanding, those coefficients are important for sampling in DDPM. And in your impl, I see that you indeed use those coefficients.

**Comment by yilundu** [comment]
Hi,

Yes, in the DDPM model, after each timestep there is a linear contraction of the input at each timestep (governed by 1 / sqrt(alpha)), but outside the linear contraction, you can write the update in line 4 of Algorithm 2 to be form of Equation 3.2. To make the connection between DDPMs and EBMs a bit more clear, we didn't explicitly add this contraction in Equation 3.2.

Best,
Yilun
