### ISSUE TITLE
Suggestion: Making sure you are aware that your HF User Access Token appears in code

### ISSUE THREAD

**Issue by Norod** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#8]
It appears in both your Colab notebook as well as here:

https://github.com/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch/blob/7e996917a7e964f63f02af14962038211e63e777/scripts/image_sample_compose_stable_diffusion.py#L28

To mitigate potential abuse of the access token, you might want to consider revoking it and (at least in the colab) use the[ login-widget ](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/stable_diffusion.ipynb)

<img width="1090" alt="Screen Shot 2022-08-31 at 18 43 19" src="https://user-images.githubusercontent.com/3617152/187721453-274e8cff-d8b3-4577-ba66-1aecdc171e49.png">

in the python file, you might want to consider passing use_auth_token=True which will use the access token stored under  ~/.huggingface/token  generated by _huggingface-cli login_

**Comment by nanlliu** [comment]
good catch! thanks just removed it.
