### ISSUE TITLE
Why not use scale and shift norm?

### ISSUE THREAD

**Issue by nnym2022** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#9]
Hi,

Great work! Is there any specific reason for not using scale shift norm for clever and ms-coco training? It seems that GLIDE and most models from improved diffusion adopted scale shift norm. Thanks in advance!

**Comment by nanlliu** [comment]
A good catch! You can def use it to improve the quality. I guess I probably forgot to enable it so I could've reported better numbers :) But it wouldn't affect much of this compositionality.
